/*
 * Copyright (c) 2009-2014 Ilya Palachev <iliyapalachev@gmail.com>
 *
 * This file is part of Polyhedra Correction Library.
 *
 * Polyhedra Correction Library is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Polyhedra Correction Library is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Polyhedra Correction Library.
 * If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file Recoverer_test.cpp
 * @brief Unit tests for Recoverer of the polyhedron.
 */

#include <unistd.h>
#include <errno.h>
#include <cstring>

#include "PolyhedraCorrectionLibrary.h"

/** The name of the test. */
#define TEST_NAME			"./Recoverer_test"

/** The number of command line arguments expected. */
#define NUM_ARGS_EXPECTED	2

/**
 * Mode of recoverer testing.
 */
enum ModeOfRecovererTesting
{
	/** Test on real shadow contour data written to file. */
	RECOVERER_REAL_TESTING,

	/** Test on synthetic model based shadow contour data. */
	RECOVERER_SYNTHETIC_TESTING
};

/**
 * The result of command line option parsing.
 */
typedef struct
{
	/** Mode of recoverer testing. */
	ModeOfRecovererTesting mode;

	/** The string with intput data location. */
	union
	{
		/** File name with existent shadow contour data. */
		char *fileName;

		/** The name of synthetic geometric figure. */
		char *figureName;
	} input;

	/**
	 * The number of contours to be generated by shadow contours constructor.
	 */
	int numContours;

	/**
	 * First angle from which the 1st shadow contour is generated.
	 */
	double shiftAngleFirst;
} CommandLineOptions;

/** Option "-f" takes the argument with file name. */
#define OPTION_FILE_NAME 'f'

/** Option "-m" takes the argument with synthetic model name */
#define OPTION_MODEL_NAME 'm'

/*
 * Option "-n" takes the argument with the number of generated contours (for
 * synthetic testing mode).
 */
#define OPTION_CONTOURS_NUMBER 'n'

/**
 * Option "-a" takes the angle from which the 1st shadow contour is generated.
 */
#define OPTION_FIRST_ANGLE 'a'

/** Getopt returns '?' in case of parsing error (missing argument). */
#define GETOPT_QUESTION '?'

/**
 * Definition of the option set for recoverer test.
 */
#define RECOVERER_OPTIONS_GETOPT_DESCRIPTION "f:m:n:"


/** Error return value of getopt function. */
#define GETOPT_FAILURE -1

/**
 * Unumeration that describes possible synthetic models that can be used in
 * recoverer testing.
 */
enum RecovererTestModelID
{
	MODEL_CUBE = 0,			/**< The cube */
	MODEL_PYRAMID = 1,		/**< The pyramid */
	MODEL_PRISM = 2,		/**< The prism */
	MODEL_CUBE_CUTTED = 3	/**< The cube with a whole cutted out from it */
};

/** The number of possible test models. */
#define RECOVERER_TEST_MODELS_NUMBER	4

/** Structure describing given test model. */
typedef struct
{
	RecovererTestModelID id;	/**< The ID of model */
	const char *name;			/**< Name */
	const char *description;	/**< Description */
} RecovererTestModel;

RecovererTestModel recovererTestModels[] =
{
	{
		MODEL_CUBE,
		"cube",
		"Simple cube with coordinates of points +1 / -1."
	},
	{
		MODEL_PYRAMID,
		"pyramid",
		"Triangled pyramid with ideal triangle in bottom."
	},
	{
		MODEL_PRISM,
		"prism",
		"Triangled prism with ideal triangles in top and bottom."
	},
	{
		MODEL_CUBE_CUTTED,
		"cube_cutted",
		"The cube with a whole cutted out from it"
	}
};

/**
 * Prints the usage of the program.
 *
 * @param argc	Standard Linux argc
 * @param argv	Standard Linux argv
 */
void printUsage(int argc, char** argv)
{
	DEBUG_START;
	printf("Usage:\n");
	STDERR_PRINT("%s - Unit tests for Recoverer of the polyhedron.", TEST_NAME);
	STDERR_PRINT("Usage:\n");
	STDERR_PRINT("%s [-%c <input file name>] [-%c <model name> -%c <number of "
		"contours>]\n", TEST_NAME, OPTION_FILE_NAME, OPTION_MODEL_NAME,
		OPTION_CONTOURS_NUMBER);
	STDERR_PRINT("Options:\n");
	STDERR_PRINT("\t-%c\tThe name of file with shadow contours to be "
		"processed\n", OPTION_FILE_NAME);
	STDERR_PRINT("\t-%c\tThe name of synthetic model to be tested on.\n",
		OPTION_MODEL_NAME);
	STDERR_PRINT("\t-%c\tThe number of contours to be generated from the "
		"synthetic model\n", OPTION_CONTOURS_NUMBER);
	STDERR_PRINT("Possible synthetic models are:\n");
	for (int iModel = 0; iModel < RECOVERER_TEST_MODELS_NUMBER; ++iModel)
	{
		RecovererTestModel *model = &recovererTestModels[iModel];
		STDERR_PRINT("\t%d.\"%s\"\t- %s\n", model->id, model->name,
			model->description);
	}
	DEBUG_END;
}

/**
 * Parses command line string to obtain options from it.
 * 
 * @param argc	Standard Linux argc
 * @param argv	Standard Linux argv
 */
CommandLineOptions* parseCommandLine(int argc, char** argv)
{
	DEBUG_START;
	CommandLineOptions* options = new CommandLineOptions();
	bool ifOptionFileName = false;
	bool ifOptionModelName = false;
	bool ifOptionNumContours = false;
	long int charCurr;
	opterr = 0;

	/*
	 * Iterate command line arguments using standard Libc function getopt.
	 * See http://www.gnu.org/software/libc/manual/html_node/Getopt.html
	 * for details.
	 */
	while ((charCurr = getopt(argc, argv, RECOVERER_OPTIONS_GETOPT_DESCRIPTION))
		!= GETOPT_FAILURE)
	{
		char *charMistaken = NULL;

		switch (charCurr)
		{
		case OPTION_FILE_NAME:
			options->mode = RECOVERER_REAL_TESTING;
			options->input.fileName = optarg;
			break;
		case OPTION_MODEL_NAME:
			options->mode = RECOVERER_SYNTHETIC_TESTING;
			options->input.figureName = optarg;
			break;
		case OPTION_CONTOURS_NUMBER:
			/* Parse digital number from input argument. */
			options->numContours = strtol(optarg, &charMistaken, 10);

			/* If user gives invalid character, the charMistaken is set to it */
			if (charMistaken)
			{
				STDERR_PRINT("Cannot parse number. Invalid character %s",
					charMistaken);
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
			}

			/* In case of underflow or overflow errno is set to ERANGE. */
			if (errno == ERANGE)
			{
				STDERR_PRINT("Given number of contours is out of range");
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
			}
			break;
		case OPTION_FIRST_ANGLE:
			/* Parse floating-point number from input argument. */
			options->shiftAngleFirst = strtod(optarg, &charMistaken);

			/* If user gives invalid character, the charMistaken is set to it */
			if (charMistaken)
			{
				STDERR_PRINT("Cannot parse number. Invalid character %s",
					charMistaken);
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
			}

			/* In case of underflow or overflow errno is set to ERANGE. */
			if (errno == ERANGE)
			{
				STDERR_PRINT("Given value of angle is out of range");
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
			}
			break;
		case GETOPT_QUESTION:
			switch (optopt)
			{
			case OPTION_FILE_NAME:
				STDERR_PRINT("Option \"-%c\" requires an argument - the name of"
					" input file.", OPTION_FILE_NAME);
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
				break;
			case OPTION_MODEL_NAME:
				STDERR_PRINT("Option \"-%c\" requires an argument - the name of"
					" synthetic model to be tested.", OPTION_MODEL_NAME);
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
				break;
			case OPTION_CONTOURS_NUMBER:
				STDERR_PRINT("Option \"-%c\" requires an argument - the number "
					"contour generated from original model (in synthetic "
					"testing mode)", OPTION_CONTOURS_NUMBER);
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
				break;
			case OPTION_FIRST_ANGLE:
				STDERR_PRINT("Option \"-%c\" requires an argument -- the value "
					"of the first angle from which the first shadow contour is "
					"generated.", OPTION_FIRST_ANGLE);
				printUsage(argc, argv);
				DEBUG_END;
				exit(EXIT_FAILURE);
				break;
			default:
				ASSERT(0 && "Impossible happened.");
				DEBUG_END;
				exit(EXIT_FAILURE);
				break;
			}
			break;
		default:
			ASSERT(0 && "Impossible happened.");
			DEBUG_END;
			exit(EXIT_FAILURE);
			break;
		}

		/* Check that options "-f" and "-m" are not given at the same time. */
		if (ifOptionFileName && ifOptionModelName)
		{
			STDERR_PRINT("Options \"-%c\" and \"-%c\" cannot be given"
				" simultaneously.", OPTION_FILE_NAME, OPTION_MODEL_NAME);
			printUsage(argc, argv);
			DEBUG_END;
			exit(EXIT_FAILURE);
		}

		/* Check that option "-n" is provided for option "-m". */
		if ((ifOptionModelName && !ifOptionNumContours)
			|| (!ifOptionModelName && ifOptionNumContours))
		{
			STDERR_PRINT("Options \"-%c\" and \"-%c\" must be given"
				" simultaneously.", OPTION_MODEL_NAME, OPTION_CONTOURS_NUMBER);
			printUsage(argc, argv);
			DEBUG_END;
			exit(EXIT_FAILURE);
		}

		if (!ifOptionFileName && !ifOptionModelName)
		{
			STDERR_PRINT("At least one of options \"-%c\" and \"-%c\" must be "
				"specified", OPTION_FILE_NAME, OPTION_MODEL_NAME);
			printUsage(argc, argv);
			DEBUG_END;
			exit(EXIT_FAILURE);
		}
	}
	DEBUG_END;
	return options;
}

/**
 * The main function of the test.
 * 
 * @param argc	Standard Linux argc
 * @param argv	Standard Linux argv
 */
int main(int argc, char** argv)
{
	DEBUG_START;

	CommandLineOptions *options = parseCommandLine(argc, argv);

	PolyhedronPtr p(new Polyhedron());
	ShadeContourDataPtr SCData(new ShadeContourData(p));

	if (options->mode == RECOVERER_REAL_TESTING)
	{
		/* Read shadow contours data from file. */
		SCData->fscanDefault(options->input.fileName);
	}
	else if (options->mode == RECOVERER_SYNTHETIC_TESTING)
	{
		/* Generate shadow contour from */
		ShadeContourConstructorPtr constructor(new ShadeContourConstructor(p,
				SCData));
		constructor->run(options->numContours, options->shiftAngleFirst);
	}

	/* Run recoverer. */
	RecovererPtr recoverer(new Recoverer());
	recoverer->buildNaivePolyhedron(SCData);

	DEBUG_END;
	return EXIT_SUCCESS;
}
