/*
 * Copyright (c) 2009-2014 Ilya Palachev <iliyapalachev@gmail.com>
 *
 * This file is part of Polyhedra Correction Library.
 *
 * Polyhedra Correction Library is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Polyhedra Correction Library is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Polyhedra Correction Library.
 * If not, see <http://www.gnu.org/licenses/>.
 */

#include <unistd.h>

#include "PolyhedraCorrectionLibrary.h"

#define NUM_ARGS_EXPECTED 2

/**
 * Mode of recoverer testing.
 */
enum ModeOfRecovererTesting
{
	/** Test on real shadow contour data written to file. */
	RECOVERER_REAL_TESTING,

	/** Test on synthetic model based shadow contour data. */
	RECOVERER_SYNTHETIC_TESTING
};

/**
 * The result of command line option parsing.
 */
typedef struct
{
	/** Mode of recoverer testing. */
	ModeOfRecovererTesting mode;

	/** The string with intput data location. */
	union input
	{
		/** File name with existent shadow contour data. */
		char *fileName;

		/** The name of synthetic geometric figure. */
		char *figureName;
	};

	/**
	 * The number of contours to be generated by shadow contours constructor.
	 */
	int numContours;
} CommandLineOptions;

/** Option "-f" takes the argument with file name. */
#define OPTION_FILE_NAME 'f'

/* Option "-m" takes the argument with synthetic model name */
#define OPTION_MODEL_NAME 'm'

/*
 * Option "-n" takes the argument with the number of generated contours (for
 * synthetic testing mode).
 */
#define OPTION_CONTOURS_NUMBER 'n'

#define GETOPT_QUESTION '?'

/**
 * Definition of the option set for recoverer test.
 */
#define RECOVERER_OPTIONS_GETOPT_DESCRIPTION "f:m:n:"


/** Error return value of getopt function. */
#define GETOPT_FAILURE -1

/**
 * Parses command line string to obtain options from it.
 * 
 * @param argc	Standard Linux argc
 * @param argv	Standard Linux argv
 */
CommandLineOptions* parseCommandLine(int argc, char** argv)
{
	DEBUG_START;
	CommandLineOptions* options = new CommandLineOptions();
	bool ifOptionF = false, ifOptionM = false, ifOptionN = false;
	opterr = 0;

	/*
	 * Iterate command line arguments using standard Libc function getopt.
	 * See http://www.gnu.org/software/libc/manual/html_node/Getopt.html
	 * for details.
	 */
	while ((charCurr = getopt(argc, argv, RECOVERER_OPTIONS_GETOPT_DESCRIPTION))
		!= GETOPT_FAILURE)
	{
		switch (charCurr)
		{
		case OPTION_FILE_NAME:
			options->mode = RECOVERER_REAL_TESTING;
			options->input.fileName = optarg;
			break;
		case OPTION_MODEL_NAME:
			options->mode = RECOVERER_SYNTHETIC_TESTING;
			options->input.figureName = optarg;
			break;
		case OPTION_CONTOURS_NUMBER:
			options
			break;
		case GETOPT_QUESTION:
			break;
		default:
			ASSERT(0 && "Impossible happened.");
			break;
		}

		/* Check that options "-f" and "-m" are not given at the same time. */
		if (ifOptionF && ifOptionM)
		{
			ERROR_PRINT(stderr, "Options \"-f\" and \"-m\" cannot be given"
				" simultaneously.");
			printUsage();
			exit(EXIT_FAILURE);
		}

		/* Check that option "-n" is provided for option "-m". */
		if ((ifOptionM && !ifOptionN) || (!ifOptionM && ifOptionN))
		{
			ERROR_PRINT(stderr, "Options \"-m\" and \"-n\" must be given"
				"");
			printUsage();
			exit(EXIT_FAILURE);
		}
	}
	DEBUG_END;
}

/**
 * Prints the usage of the program.
 */
void printUsage(void)
{
	DEBUG_START;
	printf("Usage:\n");
	printf("./Recoverer_test <input file>\n");
	DEBUG_END;
}

/**
 * The main function of the test.
 * 
 * @param argc	Standard Linux argc
 * @param argv	Standard Linux argv
 */
int main(int argc, char** argv)
{
	DEBUG_START;
	if (argc != NUM_ARGS_EXPECTED)
	{
		ERROR_PRINT("Wrong arguments provided to program.");
		printUsage();
		DEBUG_END;
		return EXIT_FAILURE;
	}

	/* TODO: Here should be a good command-line parser function. */

	PolyhedronPtr p(new Polyhedron());
	ShadeContourDataPtr SCData(new ShadeContourData(p));
	SCData->fscanDefault(argv[1]);
	RecovererPtr recoverer(new Recoverer());
	recoverer->buildNaivePolyhedron(SCData);

	DEBUG_END;
	return EXIT_SUCCESS;
}
