---
abstract: ~
author:
  - 'sebastien heymann <sebastien.heymann@gephi.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-LibGEXF
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
